const GET_TEMPLATES = 'GET_TEMPLATES'
const NEW_TEMPLATE = 'NEW_TEMPLATE'
const DESTROY_TEMPLATE = 'DESTROY_TEMPLATE'
const PREVIEW_TEMPLATE = 'PREVIEW_TEMPLATE'
const UPDATE_TEMPLATE_TITLE = 'UPDATE_TEMPLATE_TITLE'
const SUBMIT_TEMPLATE = 'SUBMIT_TEMPLATE'
const GET_TEMPLATE = 'GET_TEMPLATE'

export default {
  GET_TEMPLATES,
  GET_TEMPLATE,
  NEW_TEMPLATE,
  DESTROY_TEMPLATE,
  PREVIEW_TEMPLATE,
  UPDATE_TEMPLATE_TITLE,
  SUBMIT_TEMPLATE
}



